config:
  clickable:
    - "iron_door"
    - "acacia_door"
    - "oak_door"
    - "spruce_door"
    - "birch_door"
    - "jungle_door"
    - "dark_oak_door"
    - "crimson_door"
    - "warped_door"

  blacklist:
    - "oak_fence_gate"
    - "spruce_fence_gate"
    - "birch_fence_gate"
    - "jungle_fence_gate"
    - "dark_oak_fence_gate"
    - "crimson_fence_gate"
    - "warped_fence_gate"
    - "acacia_fence:gate"
    - "iron_trapdoor"
    - "oak_trapdoor"
    - "birch_trapdoor"
    - "jungle_trapdoor"
    - "dark_oak_trapdoor"
    - "crimson_trapdoor"
    - "warped_trapdoor"
    - "acacia_trapdoor"
